### PR TITLE
Syntax improvements, and a few new terms.

### PR DESCRIPTION
**Pull request by patrickocoffeyo**
This PR re-factors a bit of the code, and adds a few new terms.

### CODE REVIEW

**Comment by jonathan-s** [comment]
Thanks for your contribution. But it seems like something broke along the way. I implemented the words though.

**Comment by patrickocoffeyo** [comment]
Thanks! This is a quickly evolving project :D

**Comment by jonathan-s** [comment]
Let your friends know and it might evolve even quicker :)

**Comment by patrickocoffeyo** [comment]
Trust me, I already have :D

**Pull request closed without merging**
